name: dsc180
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=24.3.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kaleido-core=0.2.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libiconv=1.16
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mathjax=2.7.5
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - narwhals=2.7.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=3.0
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.5.4
  - opentelemetry-api=1.37.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.3.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.0
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytz=2025.2
  - pyzmq=27.1.0
  - readline=8.3
  - referencing=0.30.2
  - rpds-py=0.22.3
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tk=8.6.15
  - torchvision=0.20.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - choreographer==1.2.1
      - iniconfig==2.3.0
      - kaleido==1.2.0
      - logistro==2.0.1
      - orjson==3.11.4
      - pluggy==1.6.0
      - pytest==9.0.1
      - pytest-timeout==2.4.0
      - simplejson==3.20.2
